CONFIG	    += console debug
HEADERS	    += censusvisualizerheader.hpp
SOURCES     += censusvisualizerheader.cpp
HEADERS	    += censusvisualizerview.hpp
SOURCES     += censusvisualizerview.cpp
HEADERS	    += censusvisualizer.hpp
SOURCES     += censusvisualizer.cpp
SOURCES     += main.cpp
QT += widgets #added for Qt5
