CONFIG	    += console debug
HEADERS	    += ../aqp/kuhn_munkres.hpp
SOURCES	    += ../aqp/kuhn_munkres.cpp
HEADERS	    += ../aqp/alt_key.hpp
SOURCES	    += ../aqp/alt_key.cpp
HEADERS	    += ../aqp/aqp.hpp
SOURCES	    += ../aqp/aqp.cpp
INCLUDEPATH += ../aqp
HEADERS	    += cell.hpp
SOURCES	    += cell.cpp
HEADERS	    += mainwindow.hpp
SOURCES	    += mainwindow.cpp
SOURCES	    += main.cpp
QT += widgets #added for Qt5
